### ISSUE TITLE
Animo.keyPath in Animo.sequence is playing wrong?

### ISSUE THREAD

**Issue by soleniacz** [eure/Animo#5]
Maybe i'm using it wrong but when I use a couple of the Animo.keyPath in Animo.sequence on CAShapeLayer only the last animation is played.

**Comment by JohnEstropia** [comment]
Hi, can you show your Animo.keyPath() and Animo.sequence() code usage?

**Comment by soleniacz** [comment]
Code below... Looks like only last is executed. Waits 2 sec an run only last Animo.KeyPath element in sequence.

Just add it to any view. And run.

    func startSqureViewPath() {

        self.view.backgroundColor = UIColor.blueColor()
        
        let mask = CAShapeLayer()
        
        self.view.layer.mask = mask
        
        let p0 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 100.0))
        
        let p1 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 150.0))
        
        let p2 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 100.0))
        
        let p3 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 150.0))
        
        self.view.layer.mask!.runAnimation(
            Animo.sequence(
                Animo.keyPath(
                    "path",
                    from: p0,
                    to: p1,
                    duration: 1.0
                ),
                Animo.keyPath(
                    "path",
                    from: p1,
                    to: p2,
                    duration: 1.0
                ),
                Animo.keyPath(
                    "path",
                    from: p2,
                    to: p3,
                    duration: 1.0
                )
            )
        )
    }

**Comment by soleniacz** [comment]
Im working on 1.2.0 Tag

**Comment by JohnEstropia** [comment]
@soleniacz Apologies for the late reply. I think the problem is the `from` and `to` values overlap. Remember that animated values are just visual values, not the actual layer model values. So the layer's actual initial and final state after each `keyPath` execution is neither the `from` and `to` values.

In short, to simulate your expected behavior, try
```swift
    self.view.backgroundColor = UIColor.blueColor()

    let mask = CAShapeLayer()

    self.view.layer.mask = mask

    let p0 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 100.0))

    let p1 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 150.0))

    let p2 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 100.0))

    let p3 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 150.0))
    mask.path = p0.CGPath
    self.view.layer.mask!.runAnimation(
        Animo.sequence(
            Animo.keyPath(
                "path",
                to: p1,
                duration: 1.0
            ),
            Animo.keyPath(
                "path",
                to: p2,
                duration: 1.0
            ),
            Animo.keyPath(
                "path",
                to: p3,
                duration: 1.0
            )
        )
    )
```

**Comment by JohnEstropia** [comment]
Note we assign `p0` as the initial path and each `keyPath` animation only corresponds to the next transition (we omit the `from` argument)

**Comment by soleniacz** [comment]
Thanks! I tried a few things but just not this.
I know about animated and visual values.
In Classic CABasicAnimation i was:

```
self.view.backgroundColor = UIColor.blueColor()
let mask = CAShapeLayer()
self.view.layer.mask = mask

let p0 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 100.0))
let p1 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 150.0))
let p2 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 100.0))
let p3 = UIBezierPath(rect: CGRectMake(0.0, 0.0, 100.0, 150.0))

mask.path = p0.CGPath

let animation = CABasicAnimation(keyPath: "path")
animation.duration = 1.0
animation.fromValue = p0
animation.toValue = p1

mask.path = p1.CGPath

...
```
